// <auto-generated />
using System;
using CheckedAppProject.DATA.CheckedAppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheckedAppProject.DATA.Migrations
{
    [DbContext(typeof(UserItemContext))]
    [Migration("20231214213536_Next")]
    partial class Next
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.ItemListTable", b =>
                {
                    b.Property<int>("ItemListTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemListTableId"));

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ItemListDestination")
                        .HasColumnType("text");

                    b.Property<string>("ItemListName")
                        .HasColumnType("text");

                    b.Property<bool>("ItemListPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("UserTableId")
                        .HasColumnType("integer");

                    b.HasKey("ItemListTableId");

                    b.HasIndex("UserTableId");

                    b.ToTable("ItemLists");
                });

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.ItemTable", b =>
                {
                    b.Property<int>("ItemTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTableId"));

                    b.Property<string>("ItemCompany")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.HasKey("ItemTableId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.UserItemTable", b =>
                {
                    b.Property<int>("ItemListTableId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemTableId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemState")
                        .HasColumnType("text");

                    b.HasKey("ItemListTableId", "ItemTableId");

                    b.HasIndex("ItemTableId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.UserTable", b =>
                {
                    b.Property<int>("UserTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTableId"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("UserAge")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("UserLogged")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserSex")
                        .HasColumnType("text");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserTableId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.ItemListTable", b =>
                {
                    b.HasOne("CheckedAppProject.DATA.Entities.UserTable", "UserTable")
                        .WithMany("ItemListTable")
                        .HasForeignKey("UserTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTable");
                });

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.UserItemTable", b =>
                {
                    b.HasOne("CheckedAppProject.DATA.Entities.ItemListTable", "ItemListTable")
                        .WithMany()
                        .HasForeignKey("ItemListTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckedAppProject.DATA.Entities.ItemTable", "ItemTable")
                        .WithMany()
                        .HasForeignKey("ItemTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemListTable");

                    b.Navigation("ItemTable");
                });

            modelBuilder.Entity("CheckedAppProject.DATA.Entities.UserTable", b =>
                {
                    b.Navigation("ItemListTable");
                });
#pragma warning restore 612, 618
        }
    }
}
