name: CIdevV2

on: 
 workflow_dispatch:
 push: 
   branches:
   - development

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v3
     
     - name: Setup .NET
       uses: actions/checkout@v3
       with:
        dotnet-version: '7.x'
        
     - name: Restore
       run: dotnet restore ./CheckedApp/CheckedApp.sln
        
     - name: Build
       run: dotnet build ./CheckedApp/CheckedApp.sln --configuration Release --no-restore

     - name: Install NUnit.ConsoleRunner
       run: nuget install NUnit.ConsoleRunner -Version 3.17.0 -DirectDownload -OutputDirectory .
     
     - name: Test with NUnit
       run: packages\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe ./CheckedApp/TestProject/bin/Debug/net7.0/TestProject.dll
